# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  pull_request:
    branches: [ "PROD" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Teste
      run: coverage run -m jogoBatalha_teste

    - name: Relatório
      run: coverage report

    - name: Log
      run: echo "PROD-1.${{github.run_number}}"
    # - name: Git Version
    #   id: vers
    #   uses: codacy/git-version@2.4.0
    # ${{steps.vers.outputs.version}}
  
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: pittaleticia/docker_pipeline
        tags: prod-1.${{github.run_number}}
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    # - uses: mr-smithers-excellent/docker-build-push@v6
    #   name: Docker_name
    #   with:
    #     image: pittaleticia/docker_pipeline
    #     tags: v1, latest
    #     registry: docker.io
    #     dockerfile: Dockerfile
    #     username: ${{secrets.DOCKER_USERNAME}}
    #     password: ${{secrets.DOCKER_PASSWORD}}
